### PR TITLE
Retrying mechanism for BAD_AUTHORIZATIONS

### LINKED ISSUE #32: Read fail due to user authorization not yet fully propagated in zookeepers.

### PR DESCRIPTION
**Pull request by efu39**
Reason of this pull request: Observing read fails with correct auth, and found it's due to authorization not fully propagated in zookeepers. Adding retry solves the problem. Close #32.

### CODE REVIEW

File: comet-accumulo/src/main/java/org/renci/comet/accumuloops/AccumuloOperationsApiImpl.java [hunk 1]
```diff
@@ -271,40 +296,63 @@ private static BatchWriter createBatchWriter(Connector conn, String table) {
      */
     public Map<String[], Value> readOneRow(Connector conn, String tableName, Text rowID, Text colFam, Text colQual, String visibility) throws TableNotFoundException, AccumuloException, AccumuloSecurityException {
         Map<String[], Value> output = new HashMap<>();
-        try {
+        Scanner scanner = null;
+        int count = 0;
+        boolean succeed = false;
+        long beginTime = System.currentTimeMillis();
+        while(!succeed) {
```
Comment (kthare10) [inline comet-accumulo/src/main/java/org/renci/comet/accumuloops/AccumuloOperationsApiImpl.java:303]: Shouldn't this loop be based on both retry counts and sleep timer. As with current implementation, we will keep on retrying until we succeed which could result in a infinite loop for invalid read/write token passed.

Retry count and sleep interval should be both configurable.

File: comet-accumulo/src/main/java/org/renci/comet/accumuloops/AccumuloOperationsApiImpl.java [hunk 2]
```diff
@@ -325,35 +373,58 @@ private static BatchWriter createBatchWriter(Connector conn, String table) {
...
-            //scanner.setBatchSize(scanOpts.scanBatchSize);
-            // Say start key is the one with key of row
-            // and end key is the one that immediately follows the row
-            scanner.setRange(new Range(rowID));
-            scanner.fetchColumn(colFam, colQual);
+        Scanner scanner = null;
+        int count = 0;
+        boolean succeed = false;
+        long beginTime = System.currentTimeMillis();
+        while(!succeed) {
```
Comment (kthare10) [inline comet-accumulo/src/main/java/org/renci/comet/accumuloops/AccumuloOperationsApiImpl.java:380]: same comment as above

File: comet-accumulo/src/main/java/org/renci/comet/accumuloops/AccumuloOperationsApiImpl.java (hunk 1 above)
Comment (efu39) [reply comet-accumulo/src/main/java/org/renci/comet/accumuloops/AccumuloOperationsApiImpl.java:303]: Retry for BAD_AUTHORIZATIONS only happens when following conditions are met: 1) it is BAD_AUTHORIZATIONS exception, 2) the user authentication is what has been set, 3) System.currentTimeMillis() <= beginTime + retryDuration. If the conditions are not met, or if it is other type of exceptions, Exception will be thrown, and Infinite loop won't happen. 
This has been tested and verified. 

Only "retryDuration" is used and retry will stop when retryDuration time has reached. 
"count" is just for logging, I think it would be helpful to fine tune the "retryDuration"  value later by analyzing the logs.

Comment (kthare10) [reply comet-accumulo/src/main/java/org/renci/comet/accumuloops/AccumuloOperationsApiImpl.java:303]: okay, understood!

Another question: Isn't step 2 redundant ?? As it will always be true since we are comparing the conn created by the incoming visibility parameter itself.
visibility.equals(conn.securityOperations().getUserAuthorizations(user).toString()

Comment (efu39) [reply comet-accumulo/src/main/java/org/renci/comet/accumuloops/AccumuloOperationsApiImpl.java:303]: If there is other head node happen to use the same user account to access accumulo then the authorization might be overwritten. In that case, conn.securityOperations().getUserAuthorizations(user).toString() will get the overwritten value.   
This shouldnt happen so if happen exception will be thrown immediately.

**Review by kthare10 — APPROVED** [review]
